# Generated by Django 2.2.28 on 2024-04-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity_file', models.FileField(upload_to='uploads/intensity/')),
                ('impact_file', models.FileField(upload_to='uploads/impact/')),
                ('attribute_file', models.FileField(upload_to='uploads/attribute/')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
