# Generated by Django 2.2.28 on 2024-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalydata',
            name='attribute_file',
            field=models.FileField(upload_to='submit/attribute/'),
        ),
        migrations.AlterField(
            model_name='anomalydata',
            name='impact_file',
            field=models.FileField(upload_to='submit/impact/'),
        ),
        migrations.AlterField(
            model_name='anomalydata',
            name='intensity_file',
            field=models.FileField(upload_to='submit/intensity/'),
        ),
    ]
