# Generated by Django 2.2.28 on 2024-05-06 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20240407_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydata',
            name='attribute_file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='anomalydata',
            name='impact_file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='anomalydata',
            name='intensity_file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
