# Generated by Django 2.2.28 on 2024-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20240506_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalydata',
            name='attribute_file_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='anomalydata',
            name='impact_file_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='anomalydata',
            name='intensity_file_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
